name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'adopt'

    - name: Build the Java application
      run: javac -d ./build ./students/src/Main.java

    - name: Run Docker Compose
      run: |
        $services = "app1", "app2"  # Update with your service names
        foreach ($service in $services) {
          docker-compose pull $service
        }
        docker-compose up -d
